### DISCUSSION TITLE
Use images as team names

### DISCUSSION THREAD

**Discussion by efkay1** [Drarig29/brackets-viewer.js#83] [Q&A] [answered]
Hi,

is it possible to use images instead of team names? I tried html <img> tags but they seem to be interpreted as strings

best regards

**Comment by Drarig29** [comment, marked as answer]
Yes, you can! First, [to display the images](https://github.com/Drarig29/brackets-viewer.js/issues/36), use:

https://github.com/Drarig29/brackets-viewer.js/blob/4a69f6cb4396d492eba037e4e6e79bec97e98227/demo/with-local-storage.html#L45-L48

You'll need to have team names even if you don't show them, so you can have names like "Team 1" for example.

After this, you'll need to set some CSS to hide names and make the overall look better. You can make your own [custom theme](https://github.com/Drarig29/brackets-viewer.js/blob/master/demo/themes/light.css) too.

Here is an example:

```css
.brackets-viewer {
  --match-width: 90px;
}

.brackets-viewer h3 {
  padding: 10px 0px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  width: var(--match-width);
}

.brackets-viewer .participant .name > img {
    width: 2em;
    height: 2em;
}

.brackets-viewer .participant .name {
    height: 2em;
    color: transparent;
    text-overflow: clip;
}

.brackets-viewer .participant .name.hint {
    text-overflow: ellipsis;
}
```
